// <auto-generated />
using System;
using BezoekersDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BezoekersDashboard.Migrations
{
    [DbContext(typeof(BezoekersDashboardContext))]
    [Migration("20190513142037_GenerateDefault")]
    partial class GenerateDefault
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BezoekersDashboard.Models.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<string>("ParkingName");

                    b.HasKey("Id");

                    b.ToTable("Parking");
                });

            modelBuilder.Entity("BezoekersDashboard.Models.Roos24", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("Exchanche_Points");

                    b.Property<int>("Recieved_Points");

                    b.Property<int?>("SponsorsId");

                    b.Property<int>("Transactions");

                    b.HasKey("Id");

                    b.HasIndex("SponsorsId");

                    b.ToTable("Roos24");
                });

            modelBuilder.Entity("BezoekersDashboard.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Sponsor");
                });

            modelBuilder.Entity("BezoekersDashboard.Models.Visitors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Zipcode");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("BezoekersDashboard.Models.Roos24", b =>
                {
                    b.HasOne("BezoekersDashboard.Models.Sponsor", "Sponsors")
                        .WithMany()
                        .HasForeignKey("SponsorsId");
                });
#pragma warning restore 612, 618
        }
    }
}
